// <auto-generated />
namespace FPTBOOK_1670_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class firstrun : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstrun));
        
        string IMigrationMetadata.Id
        {
            get { return "202203060349236_firstrun"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
